import {Platform, StatusBar, StyleSheet} from 'react-native';
const styles = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'#fff',
        paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
    },
    containerHeader:{
        height:200,
        marginTop:20,
        backgroundColor:'#E6E6FA',
        borderRadius:20,
    },
    containerInfoWallet:{
        marginTop:15,
        flex:1,
    },
    containerItem:{
        flex:0.5,
        backgroundColor:'#E6E6FA',
        height:80,
        margin:5,
        borderRadius:10,
        
    },
    containerItemTop:{
        marginLeft:10,
        marginRight:10,
        marginTop:10,
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center'
    },
    containerHeaderTop:{
        height:155,
        justifyContent:'center',
        alignItems:'center',
    },
    containerHeaderBottom:{
        height:45,
        borderTopWidth:0.75,
        borderColor:"#fff",
        marginLeft:20,
        justifyContent:'space-between',
        marginRight:20,
        display:'flex',
        flexDirection:"row",
        alignItems:'center',
    },
    containerListJar:{
        marginTop:20,
    },
    containerListJarItem:{
        height:320,
        width: "100%",
        backgroundColor:"#E6E6FA",
        borderRadius:40,
        marginTop:20,
    },
    containerListJarItem_Item:{
        height:80,
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        marginRight:15,
        marginLeft:15,
        flex:1,
    },
    scrollview:{
        marginLeft:10,
        marginRight:10, 
        marginBottom:80,
     },
     containerListJars:{
        marginTop:20,
        height:400,
        backgroundColor:"#E6E6FA",
        borderRadius:40,
        justifyContent:'center',
        alignItems:'center'
    }
});

export default styles;